<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
print('Ранг первой матрицы:', a.ndim,
      '\nРанг второй матрицы:', b.ndim, 
      '\nРазмер первой матрицы:', a.shape,
      '\nРазмер второй матрицы:', b.shape )
# ========
print(a)
print(b)

Ранг первой матрицы: 2 
Ранг второй матрицы: 2 
Размер первой матрицы: (100, 100) 
Размер второй матрицы: (100, 100)
[[0.00603937 0.52510054 0.65768719 ... 0.51161454 0.26020443 0.294714  ]
 [0.03322136 0.38173548 0.34320933 ... 0.73651159 0.53392375 0.11023256]
 [0.18528721 0.00610336 0.54214515 ... 0.92353037 0.60785153 0.30676945]
 ...
 [0.16853781 0.56073449 0.09328204 ... 0.75654784 0.65104226 0.16807718]
 [0.90997576 0.32660148 0.30230251 ... 0.4839256  0.58221613 0.79178663]
 [0.3135943  0.98929031 0.08375901 ... 0.49478097 0.26339016 0.48283787]]
[[0.82737505 0.7742068  0.24660491 ... 0.39286724 0.17601782 0.96542068]
 [0.56216268 0.24825347 0.27386091 ... 0.35469808 0.11112146 0.24127142]
 [0.99401386 0.88123079 0.44275347 ... 0.60136431 0.34841044 0.08518826]
 ...
 [0.86548513 0.10948439 0.54493128 ... 0.20073229 0.4375091  0.93687432]
 [0.20856971 0.38950642 0.01837237 ... 0.02516988 0.96856423 0.06165426]
 [0.52082077 0.01943341 0.63573643 ... 0.16331061 0.44049793 0.977326

In [5]:
# Мое решение
def mult(a,b):
    c = []
    c_rows = a.shape[0]
    c_columns = b.shape[1]

    for i in range(c_rows):
        c.append([0])
        k = 0
        while k < c_columns:
            for j in range(c_columns):
                c[i][k] += a[i][j]*b[j][k]
            k += 1
            if k != c_columns:
                c[i].append(0)
    return c

In [6]:
# Решение из интернета
def multi(a, b):
    rowsA = len(a)
    colsA = len(a[0])
    rowsB = len(b)
    colsB = len(b[0])
    C = []
    while len(C) < rowsA:
        C.append([])
        while len(C[-1]) < colsB:
            C[-1].append(0.0)
    for i in range(rowsA):
        for j in range(colsB):
            total = 0
            for ii in range(colsA):
                total += a[i][ii] * b[ii][j]
            C[i][j] = total
    return C
#     """  
#     a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
#     b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
#     return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
#     Функция принимает на вход две матрицы: a и b размерностью size x size
#     Возвращает матрицу их произведения a * b = c 

#     Реализуйте умножение матриц без использования функций из пакета numpy
#     """
    pass

In [7]:
def np_mult(first, second):
    mfirst = np.matrix(first)
    msecond = np.matrix(second)
    return mfirst @ msecond
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    pass

In [10]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)
M1

CPU times: user 547 ms, sys: 0 ns, total: 547 ms
Wall time: 545 ms


[[24.88042337517984,
  25.437301418069758,
  26.067581481930176,
  22.838518240547472,
  22.942634033987122,
  26.78624775522605,
  25.73195090418664,
  24.977239284066965,
  25.09105653051899,
  23.822729217507383,
  23.090044088370746,
  26.37908222067722,
  25.232336101090322,
  24.134953809102605,
  21.920405865913544,
  25.241950262444977,
  23.694083192991737,
  25.481594279983796,
  27.048487566107166,
  23.718829138331564,
  27.330026288502932,
  25.89475573488243,
  25.74235381069922,
  26.137120506269152,
  25.618444342997893,
  24.487595819307167,
  25.92528437268719,
  23.511155347995217,
  26.93450064059181,
  27.66185731691656,
  24.112577498564818,
  25.079704193074882,
  24.343941971372917,
  23.007099549136086,
  23.87266245188029,
  24.82750238860904,
  24.81669881575249,
  22.708518905504263,
  23.32650545838223,
  23.011592388314604,
  26.036140373450426,
  24.380534417393505,
  25.91821927491655,
  22.7454296921855,
  25.546824669705135,
  27.24433006449863,
  22.8

In [11]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)
M2

CPU times: user 4.58 ms, sys: 3.28 ms, total: 7.86 ms
Wall time: 27.3 ms


matrix([[24.88042338, 25.43730142, 26.06758148, ..., 28.22971878,
         26.52856529, 25.24443111],
        [26.53880387, 25.62411084, 27.79180402, ..., 28.80626745,
         27.55486909, 27.4383841 ],
        [23.72486613, 23.84368481, 23.62692412, ..., 26.71052542,
         24.85614279, 25.02779001],
        ...,
        [27.51357471, 26.50726509, 26.9735604 , ..., 29.9839991 ,
         26.97796208, 27.9832677 ],
        [27.17642284, 26.3701061 , 26.63692348, ..., 29.05131137,
         27.93785472, 28.857308  ],
        [26.53700504, 24.36940605, 24.84143902, ..., 26.49964622,
         26.10719175, 25.86206958]])

In [12]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [50]:
a = np.random.sample((1, 3))
b = np.random.sample((1, 3))
a, b

(array([[0.88585152, 0.15680882, 0.40438737]]),
 array([[0.53957679, 0.20666982, 0.69737908]]))

In [95]:
def scalar_product(a, b):
#     return sum([i[0]*i[1] for i in list(zip(a,b))])
    return sum(sum([i*j for i,j in list(zip(a,b))]))
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    pass

In [96]:
def np_scalar_product(a,b):
#     return sum(a * b)
    return a[0]@b[0]
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    pass

In [97]:
np_scalar_product(a,b)

0.7924038627342969

In [98]:
scalar_product(a,b)

0.7924038627342967

In [99]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 0 ns, sys: 123 µs, total: 123 µs
Wall time: 132 µs
CPU times: user 0 ns, sys: 67 µs, total: 67 µs
Wall time: 74.4 µs


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [117]:
def np_diag_2k(a):
    return sum([i for i in np.diag(a) if i % 2 == 0])
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    pass

In [125]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 2, 2, 5, 5],
       [6, 6, 4, 2, 9],
       [9, 3, 8, 1, 3],
       [4, 1, 3, 1, 7],
       [6, 3, 4, 6, 3]])

In [119]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 75 µs, sys: 6 µs, total: 81 µs
Wall time: 86.3 µs


16

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [120]:
def cumsum(A):
    return np.cumsum(A, axis = 1)

    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    pass

In [126]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
# A = sps.uniform.rvs(size=10**3) 
A = np.random.randint(1, 10, size=(1, 10))

%time S2 = cumsum(A)

CPU times: user 47 µs, sys: 5 µs, total: 52 µs
Wall time: 55.1 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [178]:
def np_transformation(X, a=1):
    x = X.copy()
    x[:,1::2] = a
    x[:,0::2] = x[:, 0::2]**3
    return np.concatenate((X, x[:, ::-1]), axis=1)
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    pass

In [181]:
X = np.random.randint(1, 10, size=(2,5))
%time S2 = np_transformation(X, 5)
X

CPU times: user 1.2 ms, sys: 0 ns, total: 1.2 ms
Wall time: 1.02 ms


array([[6, 6, 9, 4, 7],
       [7, 5, 9, 5, 3]])

In [182]:
np_transformation(X, 5)

array([[  6,   6,   9,   4,   7, 343,   5, 729,   5, 216],
       [  7,   5,   9,   5,   3,  27,   5, 729,   5, 343]])

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [222]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    arr = []
    counts = []
    i = 0
    c = 0
    while (i < len(a)):
        if a[i] != a[i+1]:
            arr.append(a[i])
            if i == 1:
                counts.append(1)
            else:
                c += 1
                counts.append(c)
            c = 0
        elif (a[i] == a[i+1]) and (len(a)-i == 2):
            c += 2
            arr.append(a[i])
            counts.append(c)
            break
        else:
            c += 1
        i += 1
    return arr, counts
    
    pass

In [224]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 13 µs, sys: 1e+03 ns, total: 14 µs
Wall time: 15.7 µs
